[package]
name = "libctru"
version = "0.1.0"
edition = "2018"

[features]
generate = [ "bindgen" ]

[dependencies]
drone-ctypes = "0.14.0"

[build-dependencies]
bindgen = { version = "0.58.1", optional = true }
